name: ZAP Baseline Scan

on:
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run ZAP Baseline Scan via Docker
      continue-on-error: true
      run: |
        docker run --rm \
          --user $(id -u):$(id -g) \
          -v ${{ github.workspace }}:/zap/wrk:rw \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py \
          -t https://crpn.ru:8084 \
          -r zap-report.html \
          -w zap-warnings.txt \
          -J zap-report.json \
          -g zap-report.md \
          -a -d

    - name: Upload ZAP HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zap-html-report
        path: zap-report.html

    - name: Upload ZAP warnings
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zap-warnings
        path: zap-warnings.txt

    - name: Upload ZAP JSON report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zap-report-json
        path: zap-report.json

    - name: Upload ZAP Markdown report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zap-report-md
        path: zap-report.md
