name: ZAP Baseline Scan (Docker root fix)

on:
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run ZAP Baseline Scan via Docker as root
      run: |
        set +e
        docker run --rm \
          --user root \
          -v ${{ github.workspace }}:/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable \
          /zap/zap-baseline.py \
          -t https://crpn.ru:8084 \
          -r zap-report.html \
          -w zap-warnings.txt \
          -g zap-report.md \
          -J zap-report.json \
          -a -d
        echo "ZAP scan finished with exit code $?"
      continue-on-error: true

    - name: Upload ZAP HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zap-html-report
        path: zap-report.html

    - name: Upload ZAP Markdown report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zap-md-report
        path: zap-report.md

    - name: Upload ZAP JSON report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zap-json-report
        path: zap-report.json

    - name: Upload ZAP warnings
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zap-warnings
        path: zap-warnings.txt
